# Generated by Django 4.2 on 2024-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Empleado', models.CharField(max_length=8)),
                ('contrasena_Empleado', models.CharField(max_length=20)),
            ],
        ),
    ]
