# Generated by Django 4.2 on 2024-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEmpleado', models.CharField(max_length=8)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
    ]
