# Generated by Django 4.2 on 2024-02-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='numeroEmpleado',
            new_name='numero_Empleado',
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
    ]
