# Generated by Django 4.2 on 2024-02-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_administrador_numero_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'managed': False},
        ),
    ]
