# Generated by Django 4.2 on 2024-02-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_administrador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
    ]
