# Generated by Django 4.2 on 2024-02-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_Empleado', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
            ],
        ),
    ]
