# Generated by Django 4.2 on 2024-02-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrador',
        ),
    ]
