# Generated by Django 4.2 on 2024-02-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0002_delete_administrador'),
        ('ingreso', '0002_delete_customuser'),
    ]

    operations = [
    ]
